version: '3.1'

services:
  db:
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: visitations
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  visitation-tracker:
    build: .
    ports:
      - "8082:8082"
    environment:
      PORT: "8082"
      PROFILE: "dev"
      SS_JDBC_URL: "jdbc:postgresql://db:5432/visitations"
      SS_JDBC_USER: "admin"
      SS_JDBC_PASSWORD: "admin"
      SERVER_PORT: "8082"
      DATABASESERVER_PORT: "5432"
    depends_on:
      - db