
server:
  port: "${PORT:8082}"
  servlet:
    context-path: "/api/v1"
spring:
  application:
    name: visitation-tracker
  datasource:
    url: "${JDBC_URL:jdbc:postgresql://localhost:5432/visitations}"
    username: "${JDBC_USER:postgres}"
    password: "${JDBC_PASSWORD:postgres}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "${EMAIL:admin}"
    password: "${PASSWORD:admin}"
    properties.mail.smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls.enable: true

#logging:
#  level:
#    ROOT: DEBUG
